import { Platform } from 'react-native'

export const T = {
  color: {
    transparent: 'transparent',
    primary: '#667eea',
    primaryDark: '#5568d3',
    primaryLight: '#7c8ef0',
    background: '#f7fafc',
    backgroundCard: '#ffffff',
    textPrimary: '#1a202c',
    textSecondary: '#718096',
    textTertiary: '#a0aec0',
    border: '#e2e8f0',
    borderFocus: '#667eea',
    error: '#f56565',
    errorBackground: '#fff5f5',
    errorBorder: '#f56565',
    success: '#48bb78',
    successBackground: '#f0fff4',
    white: '#ffffff',
    black: '#000000',
    shadow: '#667eea',
    shadowDark: '#000000',
    disabled: '#cbd5e0',
    overlay: 'rgba(0, 0, 0, 0.5)',
    warning: '#f59e0b',
  },
  font: {
    size: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 20,
      xxl: 24,
      xxxl: 28,
      huge: 36,
      massive: 42,
      giant: 48,
    },
    weight: {
      regular: '400' as const,
      medium: '500' as const,
      semibold: '600' as const,
      bold: '700' as const,
    },
    family: {
      primary: Platform.select({
        ios: 'System',
        android: 'Roboto',
        default: 'System',
      }),
    },
  },
  spacing: {
    none: 0,
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
    huge: 40,
    massive: 60,
    giant: 80,
  },
  border: {
    width: {
      none: 0,
      thin: 1,
      medium: 2,
      thick: 4,
    },
    radius: {
      none: 0,
      sm: 8,
      md: 12,
      lg: 16,
      xl: 20,
      xxl: 24,
      full: 9999,
    },
  },
  shadow: {
    small: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    medium: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
    large: {
      shadowColor: '#667eea',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    },
    primary: {
      shadowColor: '#667eea',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 8,
    },
  },
  size: {
    button: {
      height: 56,
      heightSmall: 44,
      heightLarge: 64,
    },
    input: {
      height: 56,
      heightSmall: 44,
    },
    icon: {
      xs: 16,
      sm: 20,
      md: 24,
      lg: 32,
      xl: 40,
    },
    avatar: {
      small: 40,
      medium: 60,
      large: 80,
      xlarge: 120,
    },
    backButton: 40,
    iconContainer: 48,
  },
  animation: {
    duration: {
      fast: 150,
      normal: 300,
      slow: 500,
    },
    scale: {
      press: 0.95,
      hover: 1.05,
    },
  },
  layout: {
    screenPadding: 24,
    cardPadding: 20,
    sectionSpacing: 40,
  },
}

export type Theme = typeof T
